/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_deyu_stupidgameone_motion_Move */

#ifndef _Included_com_deyu_stupidgameone_motion_Move
#define _Included_com_deyu_stupidgameone_motion_Move
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_deyu_stupidgameone_motion_Move
 * Method:    init
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_deyu_stupidgameone_motion_Move_init
  (JNIEnv *, jobject);

/*
 * Class:     com_deyu_stupidgameone_motion_Move
 * Method:    getWhereToGo
 * Signature: (IIIIIII)I
 */
JNIEXPORT jint JNICALL Java_com_deyu_stupidgameone_motion_Move_getWhereToGo
  (JNIEnv *, jobject, jint, jint, jint, jint, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
